### ISSUE TITLE
PC pairing failure on Retropie 4.4

### ISSUE THREAD

**Issue by mikey-wikey** [TechWizTime/moonlight-retropie#17]
Script doesn't work properly in the newest build of Retropie. 

Would love if it can be fixed.

**Comment by ramingar** [comment]
maybe ldconfig can be a solution?

**Comment by tommitytom** [comment]
This script was written when RetroPie was based on Raspbian jessie, and it is not based on stretch.  You need to change any instance of "jessie" in the script with "stretch".

**Comment by tommitytom** [comment]
Also, if you've upgraded RetroPie from jessie to stretch, you'll need to make sure that your `/etc/apt/sources.list` is up to date: `deb http://archive.itimmer.nl/raspbian/moonlight jessie main` should become `deb http://archive.itimmer.nl/raspbian/moonlight stretch main`.  Follow that up with `sudo apt update && sudo apt upgrade`

**Comment by mikey-wikey** [comment]
@tommitytom That's it !! Thanks a lot for the help mate !

**Comment by thesandlord** [comment]
Is there a way to detect what OS you are running in the script and choose the right source? Should be fairly simple right? If no one is working on this, I'll take a crack at it.

**Comment by tommitytom** [comment]
You could parse the output from `lsb_release -a` :)

**Comment by thesandlord** [comment]
Cool, that worked great. Sending PR now!

#21
