### ISSUE TITLE
Invalid Number

### ISSUE THREAD

**Issue by INerevar** [TechWizTime/moonlight-retropie#4]
After calling sudo ./moonlight.sh, the script starts and shows "Make sure you have done the following", press anykey to continue, pressing any key will show the Main Menu but also end the script throwing "INVALID NUMBER!" regardless of what key has been pressed, even pressing numbers 1 - 6 will end the script with "INVALID NUMBER!"

I am trying to run this script on a Raspberry Pi 3 using RetroPie 4.3.1

**Comment by INerevar** [comment]
Removal of line 28 allows the script to complete successfully

**Comment by TechWizTime** [comment]
This has been fixed :)
